{% set version = "0.2.0" %}

package:
  name: cherab-inversion
  version: {{ version }}

source:
  url: https://github.com/munechika-koyo/cherab_inversion/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 021e5bbb1e68442fe69b17686b538e35fd17e94a53f924f9e1394babb02da5da

build:
  skip: true  # [py<39]
  skip: true  # [ppc64le and python_impl == "pypy"]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0                           # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('clang') }}                # [win]
  host:
    - python
    - wheel
    - cython >=3.0
    - numpy
    - meson-python >=0.13
    - pkg-config
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - scikit-sparse

test:
  imports:
    - cherab.inversion
  commands:
    - pip check
    - pytest --pyargs cherab.inversion
  requires:
    - pip
    - pytest

about:
  home: https://cherab-inversion.readthedocs.io/en/stable/
  summary: Cherab inversion framework
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://cherab-inversion.readthedocs.io/en/stable/
  dev_url: https://github.com/munechika-koyo/cherab_inversion

extra:
  recipe-maintainers:
    - munechika-koyo
