{% set version = "0.3.0" %}

package:
  name: cherab-inversion
  version: {{ version }}

source:
  url: https://github.com/munechika-koyo/cherab_inversion/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fc924472ca446a1ea70109de2b6be1f9428d360656df17b72573673fa7191a90

build:
  noarch: python
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv

requirements:
  host:
    - pip
    - python
    - meson-python
    - wheel
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - scikit-sparse

test:
  imports:
    - cherab.inversion
  commands:
    - pip check
    - pytest --pyargs cherab.inversion
  requires:
    - pip
    - pytest

about:
  home: https://cherab-inversion.readthedocs.io/en/stable/
  summary: Cherab inversion framework
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://cherab-inversion.readthedocs.io/en/stable/
  dev_url: https://github.com/munechika-koyo/cherab_inversion

extra:
  recipe-maintainers:
    - munechika-koyo
