{% set version = "0.1.5" %}

package:
  name: cherab-inversion
  version: {{ version }}

source:
  url: https://github.com/munechika-koyo/cherab_inversion/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2e6a1358d62d84cffc7ea02eb401fd95cba467911edf57ad3926d4b9d57b3b42

build:
  skip: true  # [py<39]
  skip: true  # [ppc64le and python_impl == "pypy"]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0                           # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('clang') }}                # [win]
  host:
    - python
    - wheel
    - cython >=3.0
    - numpy
    - meson-python >=0.13
    - pkg-config
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - scikit-sparse

test:
  imports:
    - cherab.inversion
  commands:
    - pip check
    - pytest --pyargs cherab.inversion
  requires:
    - pip
    - pytest

about:
  home: https://cherab-inversion.readthedocs.io/en/stable/
  summary: Cherab inversion framework
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://cherab-inversion.readthedocs.io/en/stable/
  dev_url: https://github.com/munechika-koyo/cherab_inversion

extra:
  recipe-maintainers:
    - munechika-koyo
