{% set version = "0.3.0" %}

package:
  name: cherab-inversion-split
  version: {{ version }}

source:
  url: https://github.com/munechika-koyo/cherab_inversion/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 324a9f28be801496f84739746388e20850007921e30a4b651b4b62f37d40a333

build:
  noarch: python
  number: 1

requirements:
  build:
    - python >=3.9            # [build_platform != target_platform]
    - meson-python            # [build_platform != target_platform]
    - wheel                   # [build_platform != target_platform]
    - pkg-config              # [build_platform != target_platform]
  host:
    - pip
    - python >=3.9
    - meson-python
    - meson <1.4
    - wheel
    - pkg-config
    - python-build


# the top-level build.{sh,bat} builds cherab-inversion, and then
# build-output.{sh,bat} installs the files
output:
  - name: cherab-inversion
    script: build-output.sh   # [not win]
    script: build-output.bat  # [win]
    version: {{ version }}
    requirements:
      build:
        - python >=3.9                           # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python >=3.9
        - meson-python
        - wheel
        - pkg-config
        - python-build
      run:
        - python >=3.9
        - numpy
        - scipy
        - matplotlib-base
        - scikit-sparse
    test:
      imports:
        - cherab.inversion


  - name: cherab-inversion-tests
    script: build-output.sh   # [not win]
    script: build-output.bat  # [win]
    requirements:
      build:
        - python >=3.9                           # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python >=3.9
        - meson-python
        - meson <1.4
        - wheel
        - pkg-config
        - python-build
      run:
        - python >=3.9
        - numpy
        - scipy
        - matplotlib-base
        - scikit-sparse
    test:
      requires:
        - pytest
      commands:
        - pytest --pyargs cherab.inversion


about:
  home: https://cherab-inversion.readthedocs.io/en/stable/
  summary: Cherab inversion framework
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://cherab-inversion.readthedocs.io/en/stable/
  dev_url: https://github.com/munechika-koyo/cherab_inversion

extra:
  recipe-maintainers:
    - munechika-koyo
  feedstock-name: cherab-inversion
